apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mcpo
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: mcp
  source:
    repoURL: https://arbuzov.github.io/mcp-helm/
    targetRevision: 0.2.7
    chart: mcpo
    helm:
      values: |
        existingConfigSecret: mcpo-secrets
        image:
          tag: git-39b4867@sha256:f06525afac6b5d7c0712d6ec72f85203409c3285aad4a1acb977be16e409417b
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "384Mi"
            cpu: "300m"
        ingress:
          enabled: true
          className: nginx
          annotations:
            nginx.ingress.kubernetes.io/auth-type: basic
            nginx.ingress.kubernetes.io/auth-secret: mcp-basic-auth
            nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
          path: /mcpo
          hosts:
            - dev.whitediver.keenetic.link
            - "*"
        config:
          mcpServers:
            jira:
              type: streamable_http
              url: http://mcp-atlassian-jira:8000/mcp/jira
            confluence:
              type: streamable_http
              url: http://mcp-atlassian-confluence:8000/mcp/confluence
            home-assistant:
              type: sse
              url: http://192.168.99.89:8123/mcp_server/sse
              headers:
                Authorization: "Bearer REPLACE_WITH_HOMEASSISTANT_LLAT"
  destination:
    server: https://kubernetes.default.svc
    namespace: mcp
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
