apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg-operator
  namespace: argo-cd
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system
  source:
    repoURL: https://cloudnative-pg.github.io/charts
    chart: cloudnative-pg
    targetRevision: 0.29.0
    helm:
      values: |
        replicaCount: 1
        crds:
          create: false
        monitoring:
          podMonitorEnabled: false
        resources:
          requests:
            cpu: 50m
            memory: 96Mi
          limits:
            memory: 192Mi
        affinity:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                preference:
                  matchExpressions:
                    - key: kubernetes.io/hostname
                      operator: In
                      values:
                        - kube-master
                        - kube-worker-3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ServerSideDiff=true
