apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wg-vless-gateway
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: networking
  source:
    repoURL: git@github.com:Arbuzov/home-k8s-helm.git
    targetRevision: main
    path: arbuzov/networking/wg-vless-gateway
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: vpn
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
