apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus
    targetRevision: 28.7.0
    helm:
      values: |
        server:
          statefulSet:
            enabled: false
          persistentVolume:
            enabled: false
          persistent:
            enabled: false
          ingress:
            enabled: true
            ingressClassName: nginx
            hosts: ['dev.whitediver.keenetic.link', '']
            path: /prometheus
            tls:
              - secretName: dev.whitediver.keenetic.link-tls
                hosts: ['dev.whitediver.keenetic.link']
          baseURL: /prometheus
          prefixURL: /prometheus
          resources:
            limits:
              cpu: 150m
              memory: 768Mi
            requests:
              cpu: 150m
              memory: 768Mi
        alertmanager:
          enabled: false
          ingressClassName: "nginx"
        forceNamespace: "prometheus"
        extraScrapeConfigs: |
          - job_name: cloudnative-pg
            kubernetes_sd_configs:
              - role: pod
            relabel_configs:
              - source_labels: [__meta_kubernetes_pod_label_cnpg_io_cluster]
                regex: .+
                action: keep
              - source_labels: [__meta_kubernetes_pod_container_port_number]
                regex: "9187"
                action: keep
              - source_labels: [__meta_kubernetes_namespace]
                target_label: namespace
              - source_labels: [__meta_kubernetes_pod_name]
                target_label: pod
              - source_labels: [__meta_kubernetes_pod_label_cnpg_io_cluster]
                target_label: cluster
              - source_labels: [__meta_kubernetes_pod_node_name]
                target_label: node
          - job_name: argo-cd
            kubernetes_sd_configs:
              - role: pod
                namespaces:
                  names: [argo-cd]
            relabel_configs:
              - source_labels: [__meta_kubernetes_pod_container_port_name]
                regex: metrics
                action: keep
              - source_labels: [__meta_kubernetes_namespace]
                target_label: namespace
              - source_labels: [__meta_kubernetes_pod_name]
                target_label: pod
              - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_component]
                target_label: component
        prometheus-node-exporter:
          resources:
            limits:
              cpu: 100m
              memory: 32Mi
            requests:
              cpu: 100m
              memory: 32Mi
        kube-state-metrics:
          resources:
            limits:
              cpu: 150m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
        prometheus-pushgateway:
          resources:
            limits:
              cpu: 100m
              memory: 64Mi
            requests:
              cpu: 25m
              memory: 32Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
