apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: influxdb
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://helm.influxdata.com/
    targetRevision: 4.12.1
    chart: influxdb
    helm:
      values: |
        image:
          repository: arm64v8/influxdb
          tag: 1.8.10
        service:
          type: LoadBalancer
          loadBalancerIP: "192.168.99.44"
          externalIPs:
            - 192.168.99.44
        nodeAffinityPreset:
          type: hard
          key: kubernetes.io/hostname
          values:
          - kube-master
        nodeSelector:
          kubernetes.io/hostname: kube-master
        persistence:
          enabled: true
          storageClass: "local-path"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "2Gi"
            cpu: "500m"
        livenessProbe:
          path: "/ping"
          initialDelaySeconds: 600
          timeoutSeconds: 5
        startupProbe:
          enabled: true
          path: "/ping"
          failureThreshold: 120
          periodSeconds: 10
        config:
          monitor:
            store-enabled: false
          data:
            index-version: "tsi1"
            cache-max-memory-size: "512m"
            cache-snapshot-memory-size: "64m"
            cache-snapshot-write-cold-duration: "10m"
            max-concurrent-compactions: 1
            compact-full-write-cold-duration: "8760h"
  destination:
    server: https://kubernetes.default.svc
    namespace: influxdb
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /spec/volumeClaimTemplates
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ServerSideDiff=true
