apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keenetic-grafana-monitoring
  namespace: argo-cd
spec:
  project: observability
  source:
    repoURL: git@github.com:Arbuzov/home-k8s-helm.git
    targetRevision: HEAD
    path: arbuzov/observability/keenetic-grafana-monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: influxdb
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
