apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oauth2-proxy
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: mcp
  source:
    repoURL: https://oauth2-proxy.github.io/manifests
    chart: oauth2-proxy
    targetRevision: 10.7.0
    helm:
      values: |
        config:
          existingSecret: oauth2-proxy

        extraArgs:
          provider: google
          redirect-url: https://notes.whitediver.keenetic.link/oauth2/callback
          reverse-proxy: "true"
          set-xauthrequest: "true"
          cookie-secure: "true"
          cookie-domain: .whitediver.keenetic.link
          whitelist-domain: .whitediver.keenetic.link
          email-domain: "*"

        authenticatedEmailsFile:
          enabled: true
          persistence: configmap
          restricted_access: |-
            info@whitediver.com

        ingress:
          enabled: true
          className: nginx
          path: /oauth2
          pathType: Prefix
          hosts:
            - notes.whitediver.keenetic.link
          annotations:
            nginx.ingress.kubernetes.io/ssl-redirect: "false"

        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            memory: 128Mi

  destination:
    server: https://kubernetes.default.svc
    namespace: mcp
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
