apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mcp-gateway
  namespace: mcp
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: mcp-basic-auth
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  rules:
    - host: dev.whitediver.keenetic.link
      http:
        paths:
          - path: /mcp/jira
            pathType: Prefix
            backend:
              service:
                name: oathkeeper-proxy
                port:
                  number: 4455
          - path: /mcp/confluence
            pathType: Prefix
            backend:
              service:
                name: oathkeeper-proxy
                port:
                  number: 4455
