apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mcp-kubernetes
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: mcp
  source:
    repoURL: git@github.com:Arbuzov/home-k8s-helm.git
    targetRevision: 05caeb03be49a8f5df8237e032ca20133d13164d
    path: arbuzov/mcp/kubernetes
    helm:
      values: |
        readOnly: false
        rbac:
          clusterRole:
            rules:
              - apiGroups: ["*"]
                resources: ["*"]
                verbs: ["*"]
        resources:
          requests:
            cpu: 25m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 256Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: mcp
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
