apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mcp-kubernetes
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: mcp
  source:
    repoURL: git@github.com:Arbuzov/home-k8s-helm.git
    targetRevision: HEAD
    path: arbuzov/mcp/kubernetes
    helm:
      values: |
        readOnly: false
        rbac:
          clusterRole:
            rules:
              - apiGroups: ["*"]
                resources: ["*"]
                verbs: ["*"]
        resources:
          requests:
            cpu: 25m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 256Mi
        ingress:
          enabled: true
          className: nginx
          annotations:
            nginx.ingress.kubernetes.io/auth-type: basic
            nginx.ingress.kubernetes.io/auth-secret: mcp-basic-auth
            nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
          path: /mcp/kubernetes
          hosts:
            - dev.whitediver.keenetic.link
            - "*"
  destination:
    server: https://kubernetes.default.svc
    namespace: mcp
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
