apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: localstack
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: apps
  source:
    repoURL: https://helm.localstack.cloud
    targetRevision: 0.7.0
    chart: localstack
    helm:
      values: |
        image:
          repository: localstack/localstack
        extraEnvVars:
          - name: LOCALSTACK_AUTH_TOKEN
            valueFrom:
              secretKeyRef:
                name: localstack
                key: LOCALSTACK_AUTH_TOKEN
        livenessProbe:
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 6
          successThreshold: 1

        readinessProbe:
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 6
          successThreshold: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: localstack
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
