apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argo-cd
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.14.0
    helm:
      releaseName: nginx
      values: |
        controller:
          image:
            tag: v1.12.0
            digest: sha256:e6b8de175acda6ca913891f0f727bca4527e797d52688cbe9fec9040d6f6b6fa
            digestChroot: sha256:87c88e1c38a6c8d4483c8f70b69e2cca49853bb3ec3124b9b1be648edf139af3

          replicaCount: 2

          allowSnippetAnnotations: true
          enableAnnotationValidations: false
          admissionWebhooks:
            enabled: false

          service:
            externalIPs:
              - 192.168.99.44

          resources:
            requests:
              cpu: 150m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 320Mi

          livenessProbe:
            failureThreshold: 6
            periodSeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 6
            periodSeconds: 15
            timeoutSeconds: 5

          nodeSelector:
            kubernetes.io/os: linux

          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - topologyKey: kubernetes.io/hostname
                  labelSelector:
                    matchLabels:
                      app.kubernetes.io/instance: nginx
                      app.kubernetes.io/component: controller
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 100
                  preference:
                    matchExpressions:
                      - key: kubernetes.io/hostname
                        operator: In
                        values:
                          - kube-master
                          - kube-worker-3

          config:
            allow-snippet-annotations: "true"
            annotation-value-word-blocklist: ""
            client-body-buffer-size: 16k
            gzip-level: "6"
            gzip-types: application/javascript application/json text/css text/plain text/xml
            keepalive-requests: "1000"
            keepalive-timeout: "300"
            large-client-header-buffers: 4 32k
            proxy-body-size: 100m
            proxy-buffer-size: 16k
            proxy-buffering: "on"
            proxy-buffers: 8 16k
            proxy-connect-timeout: "300"
            proxy-read-timeout: "300"
            proxy-send-timeout: "300"
            upstream-keepalive-connections: "100"
            upstream-keepalive-timeout: "300"
            use-forwarded-headers: "true"
            use-gzip: "true"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ServerSideDiff=true
